version: "3.9"

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - "8080:8080"
    restart: unless-stopped

  fastapi:
    build:
      context: ./matcher
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"    # REST
      # - "6334:6334"  # gRPC가 필요하면 주석 해제
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
