version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      QDRANT_URL: http://qdrant:6333

  fastapi:
    build:
      context: ./matcher
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  qdrant_data: {}
